remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [Site Android]
description: [Site feito como projeto prático de um desafio do Curso em Vídeo.]
